# Environments
DEVICE: 0


# Object Detector
DET_MODEL_TYPE: "yolo"
DET_MODEL_PATH: './weights/yolov5s.pt'
IMG_SIZE: 640
HALF: false
OBJ_CLASSES: [0]

# Keypoint Detector
KEPT_MODEL_TYPE: "hrnet"
KEPT_MODEL_PATH: './weights/hrnet_coco_w32_256x192.pth'
KEPT_MODEL_CNF: "./configs/hrnet_coco_w32_256x192.yaml"
KEPT_HALF: false
KEPT_IMG_SIZE: [192, 256]


# Logger
LOG_LEVEL: 'info'
CONSOLE_LOG: true
CONSOLE_LOG_INTERVAL: 50
LOGGER_NAME: "POSE"
FILE_LOG: true
LOG_FILE_DIR: './log/'
LOG_FILE_COUNTER: 10
LOG_FILE_ROTATE_TIME: "D"
LOG_FILE_ROTATE_INTERVAL: 1

