# Environments
ENV:
  DEVICE: cuda     # cuda, cpu
  GPU_NUM: 0

# Media
MEDIA:
  SOURCE: 0
  OPT_AUTO: False
  FOURCC: "MJPG"
  WIDTH: 1280
  HEIGHT: 720
  FPS: 30
  REALTIME: False
  BGR: True
  ENABLE_PARAM: False
  CV_PARAM:
  - cv2.CAP_PROP_AUTO_EXPOSURE: 1
  - cv2.CAP_PROP_BRIGHTNESS: 128
  - cv2.CAP_PROP_EXPOSURE: 50

# Object Detector
DET:
  MODEL_TYPE: yolov10
  DET_MODEL_PATH: './weights/yolov10/yolov10m.pt'
  HALF: False
  CONF_THRES: 0.5
  OBJ_CLASSES: [0]
  YOLO:
    IMG_SIZE: 640
    NMS_IOU: 0.45
    AGNOSTIC_NMS: True
    MAX_DET: 100

# Keypoint Detector
KEPT:
  MODEL_TYPE: "rtmpose"     # hrnet, rtmpose
  MODEL_PATH: './weights/rtmpose/rtmpose-l_coco_256x192.onnx'
  HALF: False
  IMG_SIZE: [256, 192]    # [384,288], [256,192], [256,256]
  FORMAT: 'coco'      # coco, mpii, coco-hand

  HRNET:
    CHANNEL: 32


# Logger
LOG:
  LOG_LEVEL: 'info'
  LOGGER_NAME: "POSE"
  CONSOLE_LOG: true
  CONSOLE_LOG_INTERVAL: 100
  FILE_LOG: true
  FILE_LOG_DIR: './log/'
  FILE_LOG_COUNTER: 10
  FILE_LOG_ROTATE_TIME: "D"
  FILE_LOG_ROTATE_INTERVAL: 1

