# Environments
DEVICE: 0


# Object Detector
DET_MODEL_TYPE: "yolo"
DET_MODEL_PATH: './weights/yolov5n.pt'
IMG_SIZE: 640
HALF: false


# Keypoint Detector
KEPT_MODEL_TYPE: "hrnet"
KEPT_MODEL_PATH: './weights/hrnet_merge_w48_384x288.pth'
KEPT_MODEL_CNF: ""
KEPT_HALF: false
KEPT_IMG_SIZE: [288, 384]


# Logger
LOG_LEVEL: 'INFO'
CONSOLE_LOG: true
CONSOLE_LOG_INTERVAL: 50
LOGGER_NAME: "POSE"
FILE_LOG: true
LOG_FILE_DIR: './log/'
LOG_FILE_COUNTER: 10
LOG_FILE_ROTATE_TIME: "D"
LOG_FILE_ROTATE_INTERVAL: 1

