# Environments
ENV:
  DEVICE: cuda     # cuda, cpu
  GPU_NUM: 0

# Media
MEDIA:
  SOURCE: 0
  OPT_AUTO: False
  FOURCC: "MJPG"
  WIDTH: 1280
  HEIGHT: 720
  FPS: 30
  REALTIME: False
  BGR: True

# Object Detector
DET:
  MODEL_TYPE: yolov8
  DET_MODEL_PATH: './weights/yolov8/yolov8m.pt'
  HALF: False
  CONF_THRES: 0.5
  OBJ_CLASSES: [0]

YOLOV5:
  IMG_SIZE: 640
  NMS_IOU: 0.45
  AGNOSTIC_NMS: True
  MAX_DET: 100

YOLOV8:
  IMG_SIZE: 640
  NMS_IOU: 0.45
  AGNOSTIC_NMS: False
  MAX_DET: 100

# Keypoint Detector
KEPT_MODEL_TYPE: "hrnet"
KEPT_MODEL_PATH: './weights/hrnet_coco_w32_256x192.pth'
KEPT_MODEL_CNF: "./configs/hrnet_coco_w32_256x192.yaml"
KEPT_HALF: false
KEPT_IMG_SIZE: [256, 256]


# Logger
LOG:
  LOG_LEVEL: 'info'
  LOGGER_NAME: "POSE"
  CONSOLE_LOG: true
  CONSOLE_LOG_INTERVAL: 100
  FILE_LOG: true
  FILE_LOG_DIR: './log/'
  FILE_LOG_COUNTER: 10
  FILE_LOG_ROTATE_TIME: "D"
  FILE_LOG_ROTATE_INTERVAL: 1

